### ISSUE TITLE
EasyApplyBot/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response     raise exception_class(message, screen, stacktrace)

### ISSUE THREAD

**Issue by naanrdk** [voidbydefault/EasyApplyBot#66] opened 2024-09-22 08:37 UTC
having trouble running the project for last two weeks:
![Screenshot 2024-09-22 at 2 00 49 PM](https://github.com/user-attachments/assets/35db4496-01e7-4bff-b965-a04f91167918)

**Comment by voidbydefault** [comment] 2024-09-23 00:09
Hi @naanrdk ,

Bot is working for me in Middle Eastern profiles/account.  It happens with profiles of some regions (so far experienced with Pakistani profile). Bot looks for some element which seemingly are not there in some regional pages. You're second person to report this rare issue (so believe your account is Indian profile). Let me investigate this, I will revert. Thanks.

**Comment by voidbydefault** [comment] 2024-09-23 00:22
Bot is working fine on my Middle Eastern test account while it is failing with similar error on my Pakistani test account. It seems LinkedIn did some changes based on regions, I think debugging issue and fixing this one will take time probably. I will keep you posted.

**Comment by naanrdk** [comment] 2024-09-23 05:20
Do you want me to try changing my profile location and testing?

**Comment by voidbydefault** [comment] 2024-09-24 01:57
> Do you want me to try changing my profile location and testing?

Yes, please if possible for you without too much of inconvenience. Bot is failing here in some regions (reportedly Indo-Pak so far). 

https://github.com/voidbydefault/EasyApplyBot/blob/eb810bbe5a76302d26642e358b638990a5c987b9/linkedineasyapply.py#L227

**Comment by naanrdk** [comment] 2024-09-24 03:28
> > Do you want me to try changing my profile location and testing?
> 
> Yes, please if possible for you without too much of inconvenience. Bot is failing here in some regions (reportedly Indo-Pak so far).
> 
> https://github.com/voidbydefault/EasyApplyBot/blob/eb810bbe5a76302d26642e358b638990a5c987b9/linkedineasyapply.py#L227
Same issue even after changing location.
![Screenshot 2024-09-24 at 8 57 06 AM](https://github.com/user-attachments/assets/64db570e-3abe-4069-8c46-0026947cbbf4)

**Comment by voidbydefault** [comment] 2024-09-24 12:08
Tested once again, right now:

1. desi test account: = Fails

2. non-desi test account = 100% working:

```
Going to job page 0
Starting the application process for this page...
Starting the job application...
Application sent to Hays for the position of Recruitment Consultant
Recruitment Consultant with verification.
updated output.csv.
An application for a job at NES Fircroft has been submitted earlier.
updated output.csv.
An application for a job at Talent Harbour has been submitted earlier.
updated output.csv.
Starting the job application...
Application sent to Michels Canada for the position of Talent Acquisition Specialist
Talent Acquisition Specialist.
updated output.csv.
Starting the job application...
Application sent to Morson Talent (Canada & USA) for the position of Senior Recruitment Consultant
Senior Recruitment Consultant.
updated output.csv.
An application for a job at The New Network has been submitted earlier.
updated output.csv.
Starting the job application...
Application sent to Fractional HR Experts for the position of Human Resources Consultant
Human Resources Consultant.
updated output.csv.
An application for a job at Power Staffing Solutions has been submitted earlier.
```

**Comment by voidbydefault** [comment] 2024-09-26 14:04
@naanrdk 

Can you please try replacing: 

`
job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title')
`

With:
`
job_el = job_tile.find_element(By.XPATH, '//a[contains(@Class, "job-card-job-posting-card-wrapper__card-link")]')
`

See if it works.

**Comment by naanrdk** [comment] 2024-09-26 16:41
This works, Many thanks!

**Comment by naanrdk** [comment] 2024-09-26 16:41
This works, Many thanks!

**Comment by voidbydefault** [comment] 2024-09-26 18:27
I was able to test only now. The change above doesn't cause the bot to crash but it's not a solution. I noted that bot was stuck on first job applied and did not move to second job in queue.

Log:
Starting the job application...
Application sent to  for the position of .
updated output.csv.
An application for a job at  has been submitted earlier.
updated output.csv.
An application for a job at  has been submitted earlier.
updated output.csv.
An application for a job at  has been submitted earlier.
...
...
An application for a job at  has been submitted earlier.
updated output.csv.
(I manually clicked on next job and then...)
... Starting the job application...
Updated unprepared_questions.csv with ['text', 'how many years of work experience do you have with software as a service (saas)?'].

Please see if you note the same behavior. Needs fix IMO, opening issue again.

**Comment by naanrdk** [comment] 2024-09-26 18:28
Yes it's only applying 1st job and sleeps and then goes to 2nd page

**Comment by voidbydefault** [comment] 2024-09-26 19:02
That's correct. Bot is designed to go to sleep if a certain time has passed or a certain number of jobs are applied (to maintain average time as if a human). In this case, the situation is:

1. Bot applies on the first job,
2. Keeps applying on the same job (hence you would see "already applied").
3. Once the job count is triggered due to 2, it goes to sleep then goes to next page.
4. And the cycle repeats.

I need to find a better way to catch exact web element that is causing failure in some regional jobs page.

**Comment by naanrdk** [comment] 2024-10-02 09:25
I was thinking of raising this as a new issue. But okya, any luck?

**Comment by voidbydefault** [comment] 2024-10-03 21:28
Raising as a new issue won't help, I am handling this project alone for now. Asked a few people for support but didn't get right answer and spent quite some time trying to figure out. For now, I can confirm its affecting users in certain region (so far two cases, one from India and one from Pakistan).

I plan to try again over the weekend and in case you have some hands on skills in Python, please do try.

**Comment by naanrdk** [comment] 2024-10-07 14:07
It's working now tho
![Uploading Screenshot 2024-10-07 at 7.37.02 PM.png…]()

**Comment by voidbydefault** [comment] 2024-10-07 14:39
Do you mean the old/original code is working now? Consider getting the latest `linkedinapply.py` from my Github. Bot should prompt you like, "applied for {job_title} in {company_name}".

**Comment by voidbydefault** [comment] 2024-10-11 22:41
@naanrdk the original code should work fine now. Please check.

```
                            job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title')
                            job_el.click()
```

Result:
```
Attempting to restore previous session...
Starting the search for sales director in Pakistan.
Going to job page 0
Starting the application process for this page...
An application for a job at Zameen.com has been submitted earlier.
updated output.csv.
Starting the job application...
Application sent to Zameen.com for the position of Director Classified Sales-North.
updated output.csv.
Starting the job application...
Updated unprepared_questions.csv with ['text', 'what is your current gross salary ?'].
Application sent to Zameen.com for the position of Manager Business & Sales Effectiveness.
updated output.csv.

```


Please check and confirm to close this issue.

**Closed** 2024-10-12 03:04 UTC
Labels: bug
