### ISSUE TITLE
Issue when starting up with validating ymal

### ISSUE THREAD

**Issue by Footfungs** [voidbydefault/EasyApplyBot#64] opened 2024-07-24 16:54 UTC
below this the error is receive when i run the program

```
C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Scripts\python.exe C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\source\app\main.py 
Traceback (most recent call last):
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\source\app\main.py", line 137, in <module>
    parameters = validate_yaml()
                 ^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\source\app\main.py", line 36, in validate_yaml
    raise exc
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\source\app\main.py", line 34, in validate_yaml
    parameters = yaml.safe_load(stream)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "../config.yaml", line 153, column 1
could not find expected ':'
  in "../config.yaml", line 154, column 2

Process finished with exit code 1

```

**Comment by voidbydefault** [comment] 2024-07-25 20:41
Seems you have deleted some expected character in `config.yaml` such as `:`. Please download config again and carefully make changes.

**Comment by Footfungs** [comment] 2024-07-26 12:24
> Seems you have deleted some expected character in `config.yaml` such as `:`. Please download config again and carefully make changes.

Heyy thanks for the help and really apologize for the in convince i would love to thank you loads for helping all of us who are going through a hard time right now and i would want to teach all in my company who got laid of due to budget cuts to use it and donate as soon as they receive a job.

i am currently stuck with this error "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Scripts\python.exe C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\source\app\main.py 
Traceback (most recent call last):
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\source\app\main.py", line 138, in <module>
    browser = init_browser()
              ^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\source\app\main.py", line 24, in init_browser
    driver = webdriver.Chrome(service=service, options=browser_options,)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 55, in __init__
    self.service.start()
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self._start_process(self._path)
  File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\selenium\webdriver\common\service.py", line 208, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kitali\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kitali\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application"

**Comment by voidbydefault** [comment] 2024-07-26 16:38
Whether you donate or not, I have been responding to every issue (most were self-errors by people) just to help and also did an extended video on my [YouTube](https://www.youtube.com/@taimursm) so people can easily get started. 

Please use code tags while copying/pasting log or errors - it would help keep this thread tidy. This is the icon of code tag: 
![image](https://github.com/user-attachments/assets/1613520e-8d61-461d-af4d-8f58cedc1713)

With regards to your issuue:
> OSError: [WinError 193] %1 is not a valid Win32 application"

It seems you are on outdated version, do these steps:

1. Open Chrome browser > click on three dots > go to "Help" > go to "About Google Chrome". It will automatically update your browser in case it is running an over version

![image](https://github.com/user-attachments/assets/2dc5f4dc-3b39-40dc-ac81-03aed3fbc226)

2. Once browser is updated, open your Python IDE (hope you're using PyCharm IDE community edition), open Interpreter Settings and go to "Python Interpret". You should see following window which lists all packages. Just click once on any package then press CTRL + A (to select all packages) and click on Upgrade arrow. 

![image](https://github.com/user-attachments/assets/87871b84-c349-4963-ad73-eb2bdacab198)

3. Wait until Python IDE upgrades all packages. Once done, preferably restart your PC and it should be working.

Hope this helps. I can't make it easier that this.

Note: This is *not* an issue with bot.

**Comment by Footfungs** [comment] 2024-07-26 17:06
> Whether you donate or not, I have been responding to every issue (most were self-errors by people) just to help and also did an extended video on my [YouTube](https://www.youtube.com/@taimursm) so people can easily get started.
> 
> Please use code tags while copying/pasting log or errors - it would help keep this thread tidy. This is the icon of code tag: ![image](https://private-user-images.githubusercontent.com/101434467/352601622-1613520e-8d61-461d-af4d-8f58cedc1713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMTM4MDYsIm5iZiI6MTcyMjAxMzUwNiwicGF0aCI6Ii8xMDE0MzQ0NjcvMzUyNjAxNjIyLTE2MTM1MjBlLThkNjEtNDYxZC1hZjRkLThmNThjZWRjMTcxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxNzA1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjZhYWJiZTY2MjZjNjVjOWEyZTAyNzc3MGRiMzRlNGVmZGMxMzgwYjdhMWNlNjI5ODgyNzAyMWY1N2ZlZjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JFxc-C7ihrqymHV2nnZwoJr9kz6Eon5cRDQ26zeE8w4)
> 
> With regards to your issuue:
> 
> > OSError: [WinError 193] %1 is not a valid Win32 application"
> 
> It seems you are on outdated version, do these steps:
> 
> 1. Open Chrome browser > click on three dots > go to "Help" > go to "About Google Chrome". It will automatically update your browser in case it is running an over version
> 
> ![image](https://private-user-images.githubusercontent.com/101434467/352601983-2dc5f4dc-3b39-40dc-ac81-03aed3fbc226.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMTM4MDYsIm5iZiI6MTcyMjAxMzUwNiwicGF0aCI6Ii8xMDE0MzQ0NjcvMzUyNjAxOTgzLTJkYzVmNGRjLTNiMzktNDBkYy1hYzgxLTAzYWVkM2ZiYzIyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxNzA1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTkzMjVjNDI0M2RjZTY0ZmRhYjg5ODAxYjY1OTgyNDY5ODEyMWVmNGE4NTdlNjAwNDI0MjM0YzRmYmVkYTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2v-UspTOETJeIe1fh_2Y8ymemg5cbWd2Xijn2PwDfZE)
> 
> 2. Once browser is updated, open your Python IDE (hope you're using PyCharm IDE community edition), open Interpreter Settings and go to "Python Interpret". You should see following window which lists all packages. Just click once on any package then press CTRL + A (to select all packages) and click on Upgrade arrow.
> 
> ![image](https://private-user-images.githubusercontent.com/101434467/352602872-87871b84-c349-4963-ad73-eb2bdacab198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMTM4MDYsIm5iZiI6MTcyMjAxMzUwNiwicGF0aCI6Ii8xMDE0MzQ0NjcvMzUyNjAyODcyLTg3ODcxYjg0LWMzNDktNDk2My1hZDczLWViMmJkYWNhYjE5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxNzA1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDJlNjljNzU3NGY1MWQxZDE1ZThlNDU3Zjg4ZGY3M2NiZmY1ZDQ1NzQ5YmE1ZjgwOTUyZWY4MmE3M2E0YjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wVkVjzO-wPNyIb5X1Zu7wqFm8NsP_kBY5yIhXKHcMHg)
> 
> 3. Wait until Python IDE upgrades all packages. Once done, preferably restart your PC and it should be working.
> 
> Hope this helps. I can't make it easier that this.
> 
> Note: This is _not_ an issue with bot.

Appreciate the swift reply, the chrome version is a fresh install and no new update is available, furthermore the Packages on IDE are all updated yet i still face the same error message as before.

**Comment by voidbydefault** [comment] 2024-07-26 17:45
There is no other reason for bot to fail. Consider restarting PC if not done or Google error "OSError: [WinError 193] %1 is not a valid Win32 application" while running Python.

Bot is working at my end, I can't do more to help. Good luck.

![image](https://github.com/user-attachments/assets/4fc31f87-f3df-49cd-abc3-848df94bbdeb)

Closing.

**Closed by voidbydefault** 2024-07-26 17:45 UTC

**Comment by sampurna-d** [comment] 2024-08-01 15:56
I also started getting this same error since 2-3 days. (OSError: [WinError 193] %1 is not a valid Win32 application"). Tried updating the chrome browser as well as all the packages. Restarted the computer after that but still getting the same error. I tried on my 2 computers, both are showing same error.

**Comment by voidbydefault** [comment] 2024-08-01 18:33
This is not a bot issue, I am using it right now, Google the error to find solution. You may consider deleting `venv` virtual environment folder and setup requirements again.

**Comment by pehack** [comment] 2024-08-03 13:54
> > Seems you have deleted some expected character in `config.yaml` such as `:`. Please download config again and carefully make changes.
> 
> Heyy thanks for the help and really apologize for the in convince i would love to thank you loads for helping all of us who are going through a hard time right now and i would want to teach all in my company who got laid of due to budget cuts to use it and donate as soon as they receive a job.
> 
> i am currently stuck with this error
> 
> ```
> "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Scripts\python.exe C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\source\app\main.py 
> Traceback (most recent call last):
>   File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\source\app\main.py", line 138, in <module>
>     browser = init_browser()
>               ^^^^^^^^^^^^^^
>   File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\source\app\main.py", line 24, in init_browser
>     driver = webdriver.Chrome(service=service, options=browser_options,)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
>     super().__init__(
>   File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 55, in __init__
>     self.service.start()
>   File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
>     self._start_process(self._path)
>   File "C:\Users\Kitali\Downloads\EasyApplyBot-master\EasyApplyBot-master\venv\Lib\site-packages\selenium\webdriver\common\service.py", line 208, in _start_process
>     self.process = subprocess.Popen(
>                    ^^^^^^^^^^^^^^^^^
>   File "C:\Users\Kitali\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\Kitali\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> OSError: [WinError 193] %1 is not a valid Win32 application"
> ```

To solve this issue you have to go back to an older version of Chrome, I suggest you to use 126.0.6478.115 version, and then block Google Chrome from making updates. Until a new update of the code will be published bu Taimur.

**Comment by voidbydefault** [comment] 2024-08-03 19:15
> To solve this issue you have to go back to an older version of Chrome, I suggest you to use 126.0.6478.115 version, and then block Google Chrome from making updates. Until a new update of the code will be published bu Taimur.

Thanks for commenting @pehack. I faced this `not valid Win32' thing only once while setting bot on my friend's laptop. Resolution was using above steps (update Chrome, etc.); it started to work. I am unable to reproduce the error since then.

**Comment by ShivayeModi** [comment] 2024-08-04 17:56
@pehack , @sampurna-d , @voidbydefault , @Footfungs 
I faced the same invalid Win32 issue. To fix this I deleted the contents of C:\Users\<user-name>\.wdm\drivers\chromedriver and ran the script again. The Chrome Webdriver will be re downloaded again by web driver manager hence fixing the issue.

**Comment by voidbydefault** [comment] 2024-08-06 17:16
> To fix this I deleted the contents of C:\Users<user-name>.wdm\drivers\chromedriver and ran the script again. The Chrome Webdriver will be re downloaded again by web driver manager hence fixing the issue.

Many thanks @ShivayeModi .

**Comment by logix727** [comment] 2024-08-27 00:11
> > To fix this I deleted the contents of C:\Users.wdm\drivers\chromedriver and ran the script again. The Chrome Webdriver will be re downloaded again by web driver manager hence fixing the issue.
> 
> Many thanks @ShivayeModi .

could we use like chrome driver manager to keep this updatedc in the code?

**Comment by voidbydefault** [comment] 2024-08-27 19:58
> could we use like chrome driver manager to keep this updatedc in the code?

You don't need to. It's a one time action then it should be good to go.
