### ISSUE TITLE
Bot stuck on infinite loop when facing an unprepared question

### ISSUE THREAD

**Issue by EasyApplyBotUser** [voidbydefault/EasyApplyBot#29] opened 2023-09-26 10:41 UTC
Is there a way to make it give up when facing an application it cannot complete?

**Comment by EasyApplyBotUser** [comment] 2023-09-27 00:57
Is there a way to put an answer for unprepared questions? I know the default for experience is 1, but when it asks for something other than experience, it gets stuck

**Comment by EasyApplyBotUser** [comment] 2023-09-27 09:49
Or to make the bot automatically close the application if it gets stuck. like say after 10 attempts it will close the application and move on to the next one. i know i can manually do it. but to make it automatic would be so much better

**Comment by voidbydefault** [comment] 2023-09-28 13:11
Duplicate of #21 (see my last comment in there and contribute with error text (if possible)). Closing this one.

**Closed by voidbydefault** 2023-09-28 13:11 UTC
