### ISSUE TITLE
webdriver got an unexpected argument on MacOS

### ISSUE THREAD

**Issue by iakramdurrani** [voidbydefault/EasyApplyBot#2] opened 2023-06-23 13:48 UTC
Traceback (most recent call last):
  File "/Users/akramdurrani/PycharmProjects/EasyApplyBot/main.py", line 120, in <module>
    browser = init_browser()
  File "/Users/akramdurrani/PycharmProjects/EasyApplyBot/main.py", line 19, in init_browser
    driver = webdriver.Chrome(service=service, options=browser_options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'

Process finished with exit code 1

i get this code, how do solve this

**Comment by voidbydefault** [comment] 2023-06-23 21:38
Can you ensure Chrome browser is fully updated? The error is not because of `driver = webdriver.Chrome(service=service, options=browser_options)`

**Comment by iakramdurrani** [comment] 2023-06-23 21:48
Thank you for your reply. yes chrome is fully upto date. i am not sure why i am unable to run

**Comment by iakramdurrani** [comment] 2023-06-23 22:17
is there any way i can fix this issue?

**Comment by voidbydefault** [comment] 2023-06-23 22:50
I can suggest a few things as I am unable to reproduce this error. Try these:

- Current version of Chrome browser is Version 114.0.5735.134 (on Windows). Is it the same with you?
- I made a video that you can find in `Readme.md`. Have you followed it?
- Make a backup of your `config.yaml` and redownload the bot. Insert your `config.yaml` and see if it works.

If none of these work, try providing more details (e.g., how are you trying to run the bot, what have you tried, etc.).

**Comment by iakramdurrani** [comment] 2023-06-23 23:00
i have followed the video guidelines and i am using mac to run the code. my chrome version is 114.0.5735.133 (Official Build) (arm64). i have tried mulitple times but i face the same error again and again. i face the same issue again and again i am not sure what can be the cause of this"     driver = webdriver.Chrome(service=service, options=browser_options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'

Process finished with exit code 1

**Comment by voidbydefault** [comment] 2023-06-24 18:21
> using mac to run

I use Windows and Linux, but the culprit is Mac OS, so you have to Google and find a Mac-specific solution. Broader guidelines I am able to give are:

1. If you are using an IDE like PyCharm, consider using the Virtual Environment (venv) via terminal instead. Open `terminal` (aka the command prompt in Windows), use the `cd` command to enter the downloaded bot folder, and throw this command: `source venv/bin/activate`, then run `python3 main.py`. See if this works.

2. Alternatively, try this [link](https://stackoverflow.com/questions/22130109/cant-use-chrome-driver-for-selenium) and search for Mac-specific comments.

3. Instead of using `service` as an argument, change the code to the absolute (specific) path of `chromedriver`, e.g.:

`driver = webdriver.Chrome(executable_path="/path/to/chromedriver", options=chrome_options)`; where `/path/to/chromedriver` could be anything like `usr/local/bin` depending on where your OS is downloading the executable.

I hope the above ideas help. I will be closing this thread, as it is more about Mac OS than the bot or any of the related scripts.

**Closed by voidbydefault** 2023-06-24 18:21 UTC
